server:
  port: 8085
hm:
  swagger:
    title: 订单相关接口文档
    package: com.hmall.tarde.controller
  db:
    host: 192.168.174.128
    port: 3307
    user: root
    pw: 123
    database: hmall
feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true
    loadbalancer:
      ribbon:
        enabled: false
#logging:
#  level:
#    root: debug
